
version: "3.9"

networks:
  udpexample:
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET}
          gateway: ${GATEWAY}

services:
  base:
    image: thekyria/thekali:latest
    build:
      context: .
      dockerfile: Dockerfile
  udp_server:
    container_name: udp_server1
    image: thekyria/udp_server:latest
    depends_on:
      - base
    build:
      context: .
      dockerfile: Dockerfile.server
    network_mode: bridge
    tty: true
    stdin_open: true
    privileged: true
    entrypoint: ["/home/kali/udp_server.py", "-p"]
    command: ["${SERVER_PORT}"]
    networks:
      udpexample:
        ipv4_address: ${SERVER_IP}
  udp_client:
    container_name: udp_client1
    image: thekyria/udp_client:latest
    depends_on:
      - base
    build:
      context: .
      dockerfile: Dockerfile.client
    network_mode: bridge
    tty: true
    stdin_open: true
    privileged: true
    entrypoint: ["/home/kali/udp_client.py"]
    command: ["-a", "${SERVER_IP}", "-p", "${SERVER_PORT}"]
    networks:
      udpexample:
        ipv4_address: ${CLIENT_IP}

# Run with
#    docker compose up -d
# Cleanup corresponding images, containers and volumes
#    docker compose rm -fsv
